version: '3.9'

services:
  javaspringapi:
    container_name: javaspringapi
    image: javaspringapi:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DB_URL=jdbc:postgresql://postgredb:5432/postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - postgredb
  postgredb:
    container_name: postgredb
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}